sudo: false
language: python
python: "3.6"
install:
 - cd .. && git clone https://github.com/haikuports/haikuporter.git --depth=1 && cd haikuports
 - PATH=$PATH:../haikuporter && export PATH
 - printf 'TREE_PATH="'`pwd`'"\nPACKAGER="Nobody <server@fake>"\nTARGET_ARCHITECTURE="x86"\n' >haikuports.conf
 - wget https://github.com/waddlesplash/haiku-licenses/archive/master.zip && unzip master.zip
script:
 - ./lint-new-recipes.sh --config=haikuports.conf --licenses=haiku-licenses-master
